insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (32, '7', 'Olsztyn', 'Poland', '7/12/2024', 42);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (32, '7', 'Olsztyn', 'Poland', '7/12/2024', 42);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (32, '7', 'Olsztyn', 'Poland', '7/12/2024', 42);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (32, '7', 'Olsztyn', 'Poland', '7/12/2024', 42);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (33, '18', 'Lyon', 'France', '8/17/2022', 49);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (34, '77', 'Can-Avid', 'Philippines', '3/2/2023', 60);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (35, '91', 'Nagrumbuan', 'Philippines', '1/7/2025', 15);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (36, '100', 'Oslo', 'Norway', '8/4/2024', 36);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (37, '44', 'Moppo', 'South Korea', '1/7/2023', 37);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (38, '61', 'Donabate', 'Ireland', '12/12/2023', 38);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (39, '4', 'Rimouski', 'Canada', '3/6/2023', 23);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (40, '20', 'São Bento do Sul', 'Brazil', '10/23/2022', 33);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (41, '68', 'Kalugmanan', 'Philippines', '5/26/2024', 22);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (42, '25', 'Néa Kíos', 'Greece', '1/15/2023', 38);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (43, '42', 'Francisco I Madero', 'Mexico', '5/1/2022', 60);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (44, '93', 'Pedraza', 'Colombia', '9/17/2024', 4);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (45, '88', 'Bar-le-Duc', 'France', '7/27/2022', 37);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (46, '10', 'Daitōchō', 'Japan', '12/28/2024', 46);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (47, '97', 'Moravská Nová Ves', 'Czech Republic', '4/4/2024', 15);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (48, '59', 'Atlanta', 'United States', '11/25/2024', 31);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (136, '68', 'Launceston', 'Australia', '3/12/2025', 28);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (137, '100', 'Akita', 'Japan', '1/26/2025', 28);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (138, '44', 'Tucdao', 'Philippines', '9/24/2024', 5);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (139, '39', 'Kout na Šumavě', 'Czech Republic', '2/7/2025', 59);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (140, '93', 'Dobra', 'Poland', '7/5/2022', 55);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (141, '68', 'Matsumoto', 'Japan', '2/15/2023', 46);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (142, '84', 'Kawage', 'Japan', '3/7/2023', 37);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (143, '25', 'Ejidal', 'Mexico', '1/5/2025', 6);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (144, '50', 'Guinobatan', 'Philippines', '2/6/2023', 4);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (145, '89', 'Monte Patria', 'Chile', '6/18/2022', 44);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (146, '57', 'Chamalières', 'France', '6/15/2024', 9);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (147, '94', 'Silvino Lobos', 'Philippines', '10/11/2023', 19);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (148, '8', 'Oka', 'Canada', '5/21/2025', 37);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (149, '28', 'Hanušovice', 'Czech Republic', '4/12/2024', 50);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (150, '18', 'Gabao', 'Philippines', '12/7/2024', 42);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (151, '4', 'Cotmon', 'Philippines', '9/20/2024', 27);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (152, '19', 'Tocopilla', 'Chile', '3/4/2025', 21);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (153, '99', 'Wysoka', 'Poland', '12/2/2024', 33);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (154, '33', 'Lazaro Cardenas', 'Mexico', '3/11/2025', 46);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (155, '50', 'Tomaszów Mazowiecki', 'Poland', '12/31/2022', 1);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (156, '90', 'Loutráki', 'Greece', '1/20/2024', 8);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (157, '87', 'Loma Alta', 'Mexico', '11/3/2023', 8);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (158, '48', 'Demerval Lobão', 'Brazil', '9/14/2023', 45);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (159, '51', 'São Sebastião do Caí', 'Brazil', '12/6/2023', 54);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (160, '78', 'Rocky Mountain House', 'Canada', '7/20/2023', 17);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (161, '100', 'Néo Psychikó', 'Greece', '8/5/2022', 8);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (162, '64', 'Santa Ana', 'United States', '9/7/2022', 31);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (163, '54', 'Wólka Pełkińska', 'Poland', '2/24/2023', 17);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (164, '63', 'Lucban', 'Philippines', '3/17/2023', 24);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (165, '22', 'Garça', 'Brazil', '10/20/2023', 28);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (166, '83', 'San Francisco', 'Philippines', '5/29/2024', 44);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (167, '82', 'Podolí', 'Czech Republic', '7/11/2023', 14);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (168, '28', 'Tapiramutá', 'Brazil', '4/28/2024', 59);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (169, '26', 'Toledo', 'United States', '2/19/2024', 14);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (170, '37', 'Montluel', 'France', '11/20/2024', 48);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (171, '62', 'Belmullet', 'Ireland', '12/5/2023', 57);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (172, '29', 'Býšť', 'Czech Republic', '9/13/2024', 58);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (173, '96', 'Puerto Madryn', 'Argentina', '7/27/2022', 53);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (174, '70', 'Paiçandu', 'Brazil', '2/1/2023', 7);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (175, '71', 'Leganes', 'Spain', '2/2/2024', 24);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (176, '81', 'Cran-Gevrier', 'France', '6/19/2022', 18);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (177, '43', 'Washington', 'United States', '4/22/2023', 55);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (178, '22', 'Rio Negrinho', 'Brazil', '4/30/2022', 30);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (179, '24', 'Río Tercero', 'Argentina', '1/3/2025', 25);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (180, '45', 'Unión', 'Argentina', '2/6/2024', 39);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (181, '67', 'Lazaro Cardenas', 'Mexico', '4/24/2022', 6);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (182, '56', 'Eláteia', 'Greece', '1/6/2025', 37);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (183, '7', 'Doloplazy', 'Czech Republic', '11/24/2024', 59);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (184, '24', 'Parthenay', 'France', '6/26/2022', 51);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (185, '84', 'Pérez', 'Argentina', '7/6/2022', 36);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (186, '20', 'Ropa', 'Poland', '9/10/2024', 60);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (187, '88', 'Sasayama', 'Japan', '12/9/2024', 42);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (188, '59', 'Picton', 'New Zealand', '10/30/2024', 30);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (189, '87', 'Dassun', 'Philippines', '12/27/2024', 29);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (190, '89', 'Wright', 'Philippines', '9/22/2024', 8);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (191, '80', 'Caramay', 'Philippines', '8/24/2022', 35);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (192, '26', 'Ochojno', 'Poland', '7/1/2023', 34);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (193, '75', 'Conel', 'Philippines', '5/6/2024', 15);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (194, '77', 'Guaratuba', 'Brazil', '6/17/2024', 5);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (195, '38', 'Asahi', 'Japan', '9/29/2022', 10);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (196, '60', 'Larnaca', 'Cyprus', '1/27/2023', 58);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (2, '50', 'Hingatungan', 'Philippines', '3/24/2023', 20);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (197, '62', 'Saitama', 'Japan', '11/18/2023', 10);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (198, '5', 'El Monte', 'Chile', '6/11/2022', 42);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (199, '14', 'Santo Niño', 'Philippines', '3/4/2024', 18);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (200, '83', 'Stříbro', 'Czech Republic', '9/19/2023', 8);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (201, '96', 'Nijmegen', 'Netherlands', '4/3/2023', 38);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (202, '69', 'Meniko', 'Cyprus', '9/17/2024', 34);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (203, '29', 'Nueva Manoa', 'Bolivia', '2/12/2023', 2);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (204, '52', 'Dimiao', 'Philippines', '1/12/2023', 43);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (205, '48', 'Kapatagan', 'Philippines', '4/4/2025', 54);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (206, '2', 'Edosaki', 'Japan', '4/7/2023', 14);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (207, '17', 'Villa Regina', 'Argentina', '2/12/2024', 7);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (208, '98', 'Brněnec', 'Czech Republic', '2/23/2023', 53);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (209, '49', 'Vesoul', 'France', '1/3/2023', 32);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (210, '12', 'Saukkola', 'Finland', '8/27/2022', 11);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (211, '18', 'Malbork', 'Poland', '2/9/2023', 15);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (212, '87', 'Grenoble', 'France', '12/31/2023', 6);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (213, '23', 'Embalse', 'Argentina', '1/18/2024', 28);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (214, '86', 'Navotas', 'Philippines', '5/27/2022', 39);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (215, '87', 'Limoges', 'France', '4/29/2023', 11);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (216, '50', 'Leonídio', 'Greece', '5/26/2022', 50);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (217, '31', 'Sterling', 'United States', '2/24/2023', 50);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (218, '14', 'Villa Nueva', 'Argentina', '5/7/2025', 39);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (219, '12', 'Grenoble', 'France', '8/9/2022', 35);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (220, '22', 'Boé', 'France', '12/17/2024', 32);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (221, '29', 'Chōfugaoka', 'Japan', '12/7/2023', 27);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (222, '13', 'Cartagena', 'Spain', '5/2/2025', 54);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (223, '10', 'Waśniów', 'Poland', '4/11/2024', 42);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (224, '93', 'Newton', 'United States', '7/3/2022', 17);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (225, '73', 'Creil', 'France', '12/24/2022', 37);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (226, '69', 'Tariji', 'Philippines', '1/8/2023', 45);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (227, '58', 'Níkaia', 'Greece', '7/24/2024', 45);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (228, '95', 'Velký Týnec', 'Czech Republic', '3/11/2025', 50);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (229, '16', 'Grębków', 'Poland', '1/15/2024', 32);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (230, '99', 'Piritiba', 'Brazil', '12/16/2023', 41);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (231, '68', 'San Sebastian', 'Mexico', '9/25/2023', 2);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (232, '65', 'São Francisco do Sul', 'Brazil', '3/4/2023', 5);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (233, '95', 'Beauvais', 'France', '3/31/2025', 45);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (234, '24', 'Ciro Redondo', 'Cuba', '5/11/2022', 46);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (235, '66', 'Antigonish', 'Canada', '4/23/2025', 17);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (236, '69', 'Główczyce', 'Poland', '11/22/2023', 53);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (237, '56', 'Eaton', 'United Kingdom', '4/27/2022', 56);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (238, '5', 'Lacdayan', 'Philippines', '5/23/2023', 30);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (239, '83', 'Mukō', 'Japan', '10/3/2023', 5);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (240, '10', 'Salinas', 'United States', '5/1/2025', 20);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (241, '96', 'Trondheim', 'Norway', '11/24/2022', 39);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (242, '70', 'Emiliano Zapata', 'Mexico', '12/21/2022', 10);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (243, '73', 'Brody', 'Poland', '10/16/2022', 43);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (244, '4', 'Chuncheon', 'South Korea', '11/1/2023', 50);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (245, '19', 'Issoire', 'France', '1/6/2023', 16);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (246, '50', 'La Cruz', 'Mexico', '6/24/2024', 29);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (247, '67', 'Liljendal', 'Finland', '10/9/2023', 54);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (248, '11', 'Kinloch', 'United Kingdom', '1/30/2024', 20);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (249, '30', 'Manzanares', 'Colombia', '3/24/2025', 17);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (250, '20', 'Montréal', 'Canada', '7/2/2023', 47);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (251, '84', 'Skrzydlna', 'Poland', '2/27/2024', 44);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (252, '18', 'Śniadowo', 'Poland', '7/20/2023', 48);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (253, '76', 'Notodden', 'Norway', '2/12/2024', 48);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (254, '93', 'Áno Sýros', 'Greece', '9/16/2022', 38);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (255, '48', 'La Rochelle', 'France', '7/10/2023', 14);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (256, '60', 'Salimbalan', 'Philippines', '3/12/2025', 13);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (257, '82', 'Iława', 'Poland', '5/9/2024', 53);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (258, '41', 'Santa Cruz del Sur', 'Cuba', '11/29/2023', 42);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (259, '23', 'Sainte-Anne-des-Plaines', 'Canada', '11/8/2022', 16);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (260, '48', 'Antimácheia', 'Greece', '6/20/2024', 54);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (261, '99', 'Wąpielsk', 'Poland', '12/11/2023', 4);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (262, '80', 'San Antonio', 'Colombia', '3/31/2023', 42);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (263, '44', 'Denton', 'United Kingdom', '3/28/2024', 46);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (264, '96', 'Hastings', 'New Zealand', '4/22/2024', 44);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (265, '34', 'San Manuel', 'Philippines', '1/16/2025', 19);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (266, '60', 'Rakaia', 'New Zealand', '2/8/2025', 17);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (267, '45', 'Newmarket on Fergus', 'Ireland', '10/11/2022', 3);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (268, '89', 'Papatowai', 'New Zealand', '8/20/2024', 13);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (269, '30', 'Piekielnik', 'Poland', '11/3/2023', 3);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (270, '31', 'Bukowina Tatrzańska', 'Poland', '10/24/2022', 29);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (271, '20', 'Kukichūō', 'Japan', '6/6/2023', 49);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (272, '37', 'Kinamayan', 'Philippines', '11/3/2023', 49);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (273, '97', 'San Luis', 'Philippines', '1/10/2023', 39);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (274, '49', 'Rio Grande da Serra', 'Brazil', '4/28/2022', 1);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (275, '43', 'Vamvakoú', 'Greece', '7/14/2023', 26);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (276, '48', 'Philadelphia', 'United States', '11/6/2023', 34);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (277, '24', 'Americana', 'Brazil', '5/18/2023', 34);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (278, '28', 'Sampacho', 'Argentina', '9/28/2022', 40);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (279, '45', 'Andong', 'South Korea', '11/23/2024', 55);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (280, '83', 'Goraj', 'Poland', '5/16/2024', 48);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (281, '72', 'Ciénaga', 'Colombia', '7/6/2024', 12);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (282, '14', 'Moosomin', 'Canada', '11/4/2023', 16);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (283, '37', 'General Pico', 'Argentina', '7/11/2022', 26);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (284, '58', 'Ibarreta', 'Argentina', '5/3/2025', 52);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (285, '58', 'Omaha', 'United States', '1/5/2024', 51);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (286, '2', 'Kapatagan', 'Philippines', '10/16/2024', 5);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (287, '13', 'Velké Pavlovice', 'Czech Republic', '9/2/2023', 30);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (288, '26', 'Saint-Jean-de-Braye', 'France', '4/21/2024', 9);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (289, '100', 'Nova Venécia', 'Brazil', '4/8/2024', 55);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (290, '36', 'Vitoria-Gasteiz', 'Spain', '1/21/2025', 36);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (291, '4', 'Honkajoki', 'Finland', '10/19/2024', 48);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (292, '21', 'Newton', 'United Kingdom', '5/24/2022', 11);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (293, '46', 'Sacramento', 'United States', '12/31/2022', 3);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (294, '94', 'Białośliwie', 'Poland', '4/30/2025', 31);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (295, '85', 'Bordeaux', 'France', '6/3/2022', 20);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (296, '13', 'Talakag', 'Philippines', '9/22/2024', 50);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (297, '21', 'Mistřice', 'Czech Republic', '1/8/2024', 2);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (298, '32', 'Porangatu', 'Brazil', '5/10/2023', 41);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (299, '44', 'Quezon City', 'Philippines', '9/22/2022', 48);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (300, '66', 'Chrysó', 'Greece', '11/20/2022', 19);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (301, '51', 'Chojnice', 'Poland', '4/15/2025', 52);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (302, '99', '20 de Noviembre', 'Mexico', '11/18/2024', 12);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (303, '42', 'Rodópoli', 'Greece', '9/10/2022', 4);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (304, '5', 'Haapajärvi', 'Finland', '2/8/2025', 31);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (305, '70', 'Niedzica', 'Poland', '5/14/2024', 57);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (306, '34', 'Takayama', 'Japan', '7/23/2022', 39);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (307, '36', 'Teófilo Otoni', 'Brazil', '11/14/2022', 21);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (308, '14', 'Vernon', 'France', '10/22/2024', 33);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (309, '68', 'Kaparéllion', 'Greece', '12/12/2023', 11);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (310, '30', 'Saint-Maurice-l''Exil', 'France', '2/16/2025', 19);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (311, '6', 'Zdounky', 'Czech Republic', '7/18/2024', 39);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (312, '14', 'Tinambacan', 'Philippines', '5/22/2024', 38);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (313, '33', 'Placetas', 'Cuba', '4/11/2025', 23);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (314, '43', 'Skópelos', 'Greece', '6/19/2023', 20);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (315, '45', 'Calape', 'Philippines', '10/1/2023', 43);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (316, '53', 'Tayabo', 'Philippines', '1/2/2023', 40);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (317, '63', 'Vamvakoú', 'Greece', '8/8/2022', 6);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (318, '32', 'Los Fresnos', 'Mexico', '3/18/2025', 55);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (319, '14', 'Tabira', 'Brazil', '3/5/2024', 48);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (320, '79', 'Magbay', 'Philippines', '11/27/2024', 1);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (321, '99', 'Jardín', 'Colombia', '7/8/2024', 22);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (322, '90', 'Nueve de Julio', 'Argentina', '2/9/2025', 15);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (323, '12', 'Paracatu', 'Brazil', '6/26/2022', 6);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (324, '87', 'MacArthur', 'Philippines', '1/19/2025', 54);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (325, '21', 'Cururupu', 'Brazil', '4/22/2025', 16);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (326, '34', 'Tarragona', 'Spain', '6/20/2024', 36);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (327, '91', 'Yukuhashi', 'Japan', '3/31/2024', 17);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (328, '10', 'Tacoma', 'United States', '1/17/2025', 28);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (329, '85', 'Indaial', 'Brazil', '4/28/2023', 17);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (330, '52', 'Krotoszyn', 'Poland', '7/14/2022', 26);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (331, '54', 'Guayabal de Síquima', 'Colombia', '12/22/2023', 30);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (332, '49', 'Tucuruí', 'Brazil', '4/17/2024', 33);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (333, '95', 'San Miguel de Tucumán', 'Argentina', '5/24/2024', 38);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (334, '47', 'Inírida', 'Colombia', '9/6/2024', 5);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (335, '53', 'Gongju', 'South Korea', '10/20/2024', 20);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (336, '34', 'Lincoln', 'United States', '9/1/2024', 12);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (337, '98', 'Bourgoin-Jallieu', 'France', '10/1/2023', 40);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (338, '59', 'Seattle', 'United States', '7/31/2023', 21);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (339, '98', 'Kiamba', 'Philippines', '3/24/2023', 13);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (340, '88', 'Paris 07', 'France', '9/29/2023', 46);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (341, '77', 'Mobile', 'United States', '12/19/2022', 46);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (342, '10', 'Altkirch', 'France', '1/12/2025', 22);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (343, '58', 'Boulogne-sur-Mer', 'France', '8/17/2024', 39);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (344, '78', 'Goianira', 'Brazil', '11/18/2024', 5);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (345, '66', 'Rocky Mountain House', 'Canada', '10/6/2022', 56);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (346, '72', 'Svoboda nad Úpou', 'Czech Republic', '10/25/2024', 50);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (347, '71', 'San Pedro', 'Philippines', '9/20/2022', 44);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (348, '99', 'Uacon', 'Philippines', '10/27/2023', 24);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (349, '64', 'Santol', 'Philippines', '7/23/2022', 16);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (350, '66', 'Rimouski', 'Canada', '11/16/2024', 59);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (351, '99', 'Bulod', 'Philippines', '2/13/2025', 51);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (352, '16', 'Aroroy', 'Philippines', '7/2/2023', 1);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (353, '22', 'Kuczbork-Osada', 'Poland', '10/18/2023', 7);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (354, '42', 'Banff', 'Canada', '4/27/2024', 27);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (355, '88', 'Libato', 'Philippines', '2/11/2023', 12);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (356, '17', 'Santa Cruz', 'Mexico', '3/28/2024', 50);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (357, '82', 'Iwakura', 'Japan', '3/16/2023', 4);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (358, '41', 'Las Vegas', 'United States', '11/29/2022', 37);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (359, '22', 'Aparecida de Goiânia', 'Brazil', '6/3/2023', 19);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (360, '95', 'Periyiáli', 'Greece', '8/10/2024', 58);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (361, '51', 'T’aebaek', 'South Korea', '3/7/2024', 4);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (362, '52', 'Sodankylä', 'Finland', '8/18/2024', 41);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (363, '82', 'Maple Ridge', 'Canada', '11/22/2024', 5);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (364, '9', 'Brasília de Minas', 'Brazil', '5/7/2022', 23);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (365, '100', 'Greenville', 'United States', '11/25/2023', 7);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (366, '17', 'Giporlos', 'Philippines', '4/12/2023', 19);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (367, '92', 'Den Haag', 'Netherlands', '9/18/2022', 2);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (368, '64', 'Shimabara', 'Japan', '6/10/2022', 8);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (369, '75', 'San Isidro', 'Philippines', '5/29/2024', 25);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (370, '21', 'Bayambang', 'Philippines', '2/10/2024', 49);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (371, '8', 'Morrinhos', 'Brazil', '8/24/2024', 18);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (372, '45', 'Del Rosario', 'Philippines', '8/25/2022', 60);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (373, '86', 'Lampitak', 'Philippines', '10/13/2023', 5);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (374, '38', 'Sirib', 'Philippines', '3/30/2024', 16);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (375, '6', 'Carmen', 'Philippines', '6/26/2022', 36);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (376, '62', 'Paranapanema', 'Brazil', '11/7/2024', 29);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (377, '58', 'Rancho Nuevo', 'Mexico', '7/1/2023', 24);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (378, '71', 'Kōnosu', 'Japan', '11/4/2023', 31);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (379, '7', 'Łukowa', 'Poland', '11/14/2023', 37);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (380, '57', 'Kampokpok', 'Philippines', '5/20/2024', 35);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (381, '47', 'Pámfylla', 'Greece', '2/17/2024', 42);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (382, '20', 'Oakland', 'United States', '8/15/2023', 46);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (383, '51', 'Poá', 'Brazil', '5/31/2024', 41);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (384, '38', 'Toyohama', 'Japan', '12/6/2024', 2);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (385, '75', 'Itajuípe', 'Brazil', '4/22/2022', 30);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (386, '78', 'Nowy Duninów', 'Poland', '7/19/2022', 19);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (387, '25', 'Gujō', 'Japan', '3/1/2025', 54);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (388, '38', 'Água Preta', 'Brazil', '11/13/2023', 47);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (389, '96', 'Groningen', 'Netherlands', '8/14/2023', 16);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (390, '67', 'Tahara', 'Japan', '2/20/2023', 16);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (391, '14', 'Francisco Beltrão', 'Brazil', '8/31/2024', 49);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (392, '39', 'Polo', 'Philippines', '2/10/2023', 36);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (393, '99', 'Lípa', 'Czech Republic', '10/4/2022', 59);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (394, '69', 'La Unión', 'Colombia', '6/7/2023', 9);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (395, '60', 'San Pedro', 'Mexico', '11/2/2023', 17);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (396, '81', 'Rochester', 'United States', '5/18/2023', 28);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (397, '40', 'Všeruby', 'Czech Republic', '5/8/2025', 53);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (398, '97', 'San Isidro', 'Mexico', '2/12/2023', 44);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (399, '27', 'Pontivy', 'France', '5/22/2022', 16);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (400, '39', 'Babak', 'Philippines', '4/24/2025', 6);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (401, '90', 'Kihniö', 'Finland', '5/3/2025', 25);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (402, '40', 'Filótion', 'Greece', '7/11/2024', 56);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (403, '7', 'Sumilao', 'Philippines', '3/4/2023', 11);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (404, '65', 'Maticmatic', 'Philippines', '5/27/2022', 48);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (405, '66', 'Candoni', 'Philippines', '12/16/2022', 9);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (406, '17', 'Skorogoszcz', 'Poland', '9/27/2024', 10);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (407, '52', 'Lepanto', 'Philippines', '6/25/2022', 16);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (408, '89', 'Kępno', 'Poland', '9/4/2022', 4);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (409, '34', 'Ostaszewo', 'Poland', '7/24/2022', 36);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (410, '59', 'Mutsu', 'Japan', '1/4/2025', 34);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (411, '81', 'São Gotardo', 'Brazil', '1/16/2025', 30);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (412, '89', 'San Isidro', 'Mexico', '4/11/2024', 24);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (413, '93', 'El Refugio', 'Mexico', '4/4/2025', 2);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (414, '34', 'Toki', 'Japan', '9/30/2023', 2);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (415, '9', 'Kaustinen', 'Finland', '11/15/2024', 35);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (416, '92', 'Villa Lugano', 'Argentina', '9/27/2024', 60);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (417, '97', 'Wielka Nieszawka', 'Poland', '10/1/2023', 33);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (418, '46', 'Matalam', 'Philippines', '12/5/2023', 21);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (419, '53', 'Néa Manolás', 'Greece', '1/6/2024', 52);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (420, '89', 'Saint-Laurent-Blangy', 'France', '12/6/2022', 17);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (421, '59', 'Paniqui', 'Philippines', '2/5/2023', 47);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (422, '5', 'Bibai', 'Japan', '12/7/2022', 30);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (423, '58', 'Malalag', 'Philippines', '2/9/2023', 5);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (424, '76', 'Pittsburgh', 'United States', '11/8/2023', 15);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (425, '78', 'San Isidro', 'Mexico', '8/27/2024', 54);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (426, '45', 'Zbrosławice', 'Poland', '6/25/2024', 25);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (427, '41', 'Biguaçu', 'Brazil', '10/17/2022', 7);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (428, '65', 'Jeżów Sudecki', 'Poland', '6/26/2024', 59);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (429, '92', 'Sambuluan', 'Philippines', '2/29/2024', 11);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (430, '66', 'Bergerac', 'France', '10/9/2023', 11);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (431, '87', 'Ostroróg', 'Poland', '4/2/2025', 41);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (432, '67', 'Paris 01', 'France', '7/10/2022', 54);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (433, '14', 'Nanterre', 'France', '8/22/2024', 48);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (434, '21', 'Bordeaux', 'France', '12/15/2023', 20);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (435, '5', 'Hudlice', 'Czech Republic', '2/9/2025', 39);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (436, '86', 'Rio Negrinho', 'Brazil', '5/23/2022', 27);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (437, '44', 'Milíkov', 'Czech Republic', '2/22/2023', 39);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (438, '85', 'Masuda', 'Japan', '9/20/2022', 32);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (439, '76', 'San Agustín de Valle Fértil', 'Argentina', '4/27/2022', 55);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (440, '68', 'Toritama', 'Brazil', '7/11/2022', 43);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (441, '18', 'Kushikino', 'Japan', '4/21/2025', 10);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (442, '12', 'Nanterre', 'France', '9/29/2023', 51);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (443, '77', 'Nagareyama', 'Japan', '12/18/2023', 41);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (444, '76', 'Iriga City', 'Philippines', '11/2/2022', 23);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (445, '64', 'Wąpielsk', 'Poland', '10/13/2023', 46);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (446, '13', 'Buensuseso', 'Philippines', '6/16/2024', 11);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (447, '28', 'Courbevoie', 'France', '3/29/2025', 57);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (448, '29', 'Pittsburgh', 'United States', '11/10/2022', 55);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (449, '45', 'Loreto', 'Philippines', '11/26/2023', 44);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (450, '44', 'Leńcze', 'Poland', '8/4/2023', 36);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (451, '63', 'Borkowice', 'Poland', '10/20/2022', 57);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (452, '35', 'Pongol', 'Philippines', '10/31/2024', 4);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (453, '30', 'Kozlovice', 'Czech Republic', '10/3/2023', 50);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (454, '45', 'Muramatsu', 'Japan', '7/24/2023', 42);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (455, '2', 'Ballinroad', 'Ireland', '4/27/2022', 53);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (456, '45', 'Balma', 'France', '10/6/2024', 3);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (457, '47', 'Jasionów', 'Poland', '2/27/2023', 10);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (458, '15', 'Santa Ana', 'Philippines', '5/25/2022', 12);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (459, '18', 'Corcuera', 'Philippines', '11/13/2023', 5);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (460, '81', 'Abangay', 'Philippines', '5/1/2024', 42);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (461, '76', 'Oborniki Śląskie', 'Poland', '12/13/2024', 27);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (462, '52', 'Lukavec', 'Czech Republic', '8/14/2024', 14);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (463, '19', 'Kangaslampi', 'Finland', '6/28/2022', 43);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (464, '58', 'Santa Clara', 'Cuba', '8/16/2023', 48);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (465, '63', 'Famatina', 'Argentina', '11/25/2024', 1);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (466, '17', 'Belsk Duży', 'Poland', '4/24/2025', 20);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (467, '36', 'Néos Skopós', 'Greece', '12/12/2024', 54);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (468, '80', 'Delray Beach', 'United States', '11/29/2023', 33);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (469, '34', 'La Ceja', 'Colombia', '6/25/2022', 38);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (470, '83', 'San Antonio', 'Philippines', '12/25/2023', 20);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (471, '92', 'Ransang', 'Philippines', '4/13/2025', 3);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (472, '77', 'Esperanza', 'Philippines', '5/22/2022', 27);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (473, '92', 'Pará de Minas', 'Brazil', '4/27/2024', 32);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (474, '92', 'Szelków', 'Poland', '3/7/2025', 18);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (475, '26', 'Clarin', 'Philippines', '9/25/2024', 51);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (476, '12', 'Brześć Kujawski', 'Poland', '3/26/2023', 12);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (477, '95', 'Bantay', 'Philippines', '2/23/2023', 15);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (478, '11', 'Matão', 'Brazil', '4/5/2023', 57);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (479, '67', 'Cametá', 'Brazil', '7/12/2024', 27);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (480, '42', 'Itamaraju', 'Brazil', '9/18/2023', 44);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (481, '38', 'Świdwin', 'Poland', '9/18/2023', 24);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (482, '68', 'Calaba', 'Philippines', '3/13/2025', 16);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (483, '90', 'Raciążek', 'Poland', '11/27/2023', 22);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (484, '63', 'Camp Flora', 'Philippines', '4/19/2025', 3);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (485, '24', 'Monteros', 'Argentina', '12/28/2022', 5);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (486, '12', 'Ivry-sur-Seine', 'France', '12/14/2022', 51);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (487, '57', 'Skarżysko-Kamienna', 'Poland', '5/18/2023', 2);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (488, '41', 'Taltal', 'Philippines', '7/24/2024', 58);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (489, '89', 'Cedar Rapids', 'United States', '3/30/2023', 38);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (490, '9', 'Tromsø', 'Norway', '3/24/2024', 43);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (491, '77', 'Shiroi', 'Japan', '9/3/2024', 20);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (492, '64', 'Nanterre', 'France', '8/29/2024', 13);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (493, '68', 'Tanudan', 'Philippines', '3/23/2024', 24);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (494, '83', 'Troyes', 'France', '9/1/2023', 24);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (495, '25', 'Wawer', 'Poland', '4/4/2023', 53);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (496, '19', 'Sapporo', 'Japan', '4/3/2023', 57);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (497, '70', 'Kostakioí', 'Greece', '4/6/2023', 18);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (498, '87', 'Rionegro', 'Colombia', '8/22/2022', 8);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (499, '39', 'Igarassu', 'Brazil', '12/25/2024', 6);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (500, '61', 'Alameda', 'Mexico', '1/23/2024', 21);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (501, '80', 'Murcki', 'Poland', '9/12/2024', 35);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (502, '4', 'Jesús Menéndez', 'Cuba', '3/19/2024', 27);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (503, '10', 'Cincinnati', 'United States', '10/13/2023', 6);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (504, '79', 'Nysa', 'Poland', '2/2/2025', 48);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (505, '3', 'Lyon', 'France', '2/25/2025', 9);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (506, '38', 'Loppi', 'Finland', '7/22/2024', 11);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (507, '59', 'Puerto Madryn', 'Argentina', '9/2/2023', 34);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (508, '44', 'Miastków Kościelny', 'Poland', '11/15/2022', 18);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (509, '34', 'Jeffersonville', 'United States', '7/29/2022', 46);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (510, '21', 'Židlochovice', 'Czech Republic', '11/11/2024', 46);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (511, '53', 'Wojcieszków', 'Poland', '11/6/2022', 19);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (512, '90', 'Valença do Piauí', 'Brazil', '11/27/2022', 13);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (513, '72', 'Nuits-Saint-Georges', 'France', '7/20/2023', 24);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (514, '89', 'Sotíra', 'Cyprus', '2/11/2025', 6);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (515, '10', 'Várzea Paulista', 'Brazil', '4/16/2024', 8);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (516, '67', 'Juàzeirinho', 'Brazil', '9/13/2022', 20);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (517, '69', 'Smyków', 'Poland', '2/29/2024', 2);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (518, '100', 'São Mateus', 'Brazil', '5/31/2023', 42);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (519, '16', 'Wólka Pełkińska', 'Poland', '4/22/2024', 22);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (520, '27', 'Winnica', 'Poland', '10/4/2023', 16);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (521, '99', 'Kamsack', 'Canada', '9/21/2024', 44);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (522, '83', 'Liverpool', 'United Kingdom', '12/22/2023', 37);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (523, '58', 'Lugait', 'Philippines', '12/9/2023', 36);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (524, '11', 'Shimo-furano', 'Japan', '11/24/2022', 48);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (525, '48', 'Padre Bernardo', 'Brazil', '5/24/2022', 22);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (526, '22', 'Cheongju-si', 'South Korea', '6/27/2022', 41);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (527, '29', 'Binulasan', 'Philippines', '8/25/2024', 20);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (528, '3', 'Porsgrunn', 'Norway', '7/6/2024', 60);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (529, '91', 'Trnava', 'Czech Republic', '7/25/2024', 53);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (530, '16', 'Särkisalo', 'Finland', '6/8/2022', 21);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (531, '41', 'Amsterdam Binnenstad en Oostelijk Havengebied', 'Netherlands', '1/8/2024', 27);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (532, '36', 'Melita', 'Canada', '6/20/2022', 57);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (533, '11', 'Saint-Maixent-l''École', 'France', '9/30/2023', 25);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (534, '80', 'Minakuchi', 'Japan', '4/24/2024', 47);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (535, '44', 'Tokarnia', 'Poland', '4/9/2023', 22);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (536, '93', 'Tapilon', 'Philippines', '7/26/2022', 27);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (537, '17', 'Korisós', 'Greece', '2/23/2024', 50);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (538, '59', 'Koukkuniemi', 'Finland', '5/20/2024', 18);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (539, '22', 'Hasaki', 'Japan', '7/15/2024', 9);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (540, '82', 'Blois', 'France', '2/18/2023', 3);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (541, '91', 'Três Corações', 'Brazil', '6/24/2024', 34);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (542, '74', 'Ishikari', 'Japan', '7/11/2023', 14);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (543, '28', 'Seattle', 'United States', '6/25/2024', 44);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (544, '12', 'Tubarão', 'Brazil', '5/18/2023', 39);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (545, '76', 'T’aebaek', 'South Korea', '8/15/2023', 11);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (546, '72', 'Satsumasendai', 'Japan', '7/21/2022', 58);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (547, '28', 'Tourcoing', 'France', '1/10/2023', 17);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (548, '90', 'Palena', 'Chile', '3/17/2024', 5);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (549, '99', 'Morro Agudo', 'Brazil', '11/10/2023', 12);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (550, '81', 'Corrego Grande', 'Brazil', '11/6/2022', 37);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (551, '62', 'Hamburg', 'Germany', '1/22/2025', 7);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (552, '13', 'Skalánion', 'Greece', '7/8/2022', 27);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (553, '26', 'Valence', 'France', '3/31/2025', 26);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (554, '98', 'Arapongas', 'Brazil', '1/15/2023', 40);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (555, '52', 'Itaí', 'Brazil', '12/31/2023', 37);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (556, '7', 'Le Mans', 'France', '7/2/2024', 13);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (557, '33', 'Oklahoma City', 'United States', '12/23/2022', 48);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (558, '65', 'Dualing', 'Philippines', '4/8/2023', 30);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (559, '67', 'Świnice Warckie', 'Poland', '1/6/2025', 7);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (560, '17', 'Datagon', 'Philippines', '4/17/2025', 22);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (561, '89', 'Nice', 'France', '8/9/2023', 20);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (562, '9', 'Velký Újezd', 'Czech Republic', '8/25/2023', 36);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (563, '48', 'Las Flores', 'Mexico', '6/12/2023', 55);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (564, '10', 'Villa Bustos', 'Argentina', '1/27/2025', 16);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (565, '91', 'Getulio', 'Philippines', '3/8/2025', 49);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (566, '33', 'Isdalstø', 'Norway', '6/1/2023', 12);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (567, '89', 'Tignoan', 'Philippines', '7/31/2022', 10);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (568, '30', 'Narvacan', 'Philippines', '5/3/2022', 32);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (569, '94', 'Erie', 'United States', '3/10/2024', 35);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (570, '2', 'Černá Hora', 'Czech Republic', '10/15/2024', 55);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (571, '70', 'Siekierczyn', 'Poland', '11/5/2023', 57);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (572, '6', 'Messíni', 'Greece', '4/14/2025', 14);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (573, '25', 'Barra', 'Philippines', '1/13/2023', 51);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (574, '63', 'Upton', 'United Kingdom', '6/2/2023', 16);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (575, '90', 'Amersfoort', 'Netherlands', '1/23/2025', 43);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (576, '26', 'Boise', 'United States', '9/30/2023', 38);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (577, '93', 'Dahay', 'Philippines', '11/26/2023', 35);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (578, '96', 'København', 'Denmark', '7/20/2022', 31);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (579, '42', 'Pudoc North', 'Philippines', '3/2/2023', 55);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (580, '47', 'Steinkjer', 'Norway', '7/13/2022', 35);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (581, '26', 'Daytona Beach', 'United States', '11/17/2022', 27);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (582, '33', 'Orléans', 'France', '7/10/2023', 57);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (583, '57', 'Busay', 'Philippines', '9/2/2024', 42);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (584, '29', 'Lyon', 'France', '5/3/2022', 33);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (585, '99', 'Francisco Villa', 'Mexico', '12/30/2022', 53);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (586, '26', 'La Chapelle-sur-Erdre', 'France', '1/5/2024', 57);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (587, '39', 'København', 'Denmark', '3/18/2024', 47);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (588, '43', 'Taboc', 'Philippines', '11/30/2023', 50);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (589, '31', 'Chantepie', 'France', '2/2/2025', 56);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (590, '46', 'Eláteia', 'Greece', '12/17/2023', 36);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (591, '98', 'Maayong Tubig', 'Philippines', '3/19/2023', 44);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (592, '30', 'Kamimaruko', 'Japan', '3/5/2024', 26);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (593, '41', 'Jaboatão dos Guararapes', 'Brazil', '5/8/2025', 1);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (594, '2', 'Strzelce', 'Poland', '3/20/2024', 56);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (595, '23', 'Vaudreuil-Dorion', 'Canada', '9/11/2022', 36);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (596, '23', 'Conde', 'Brazil', '7/21/2022', 37);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (597, '9', 'Ariquemes', 'Brazil', '10/10/2023', 5);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (598, '76', 'Kivijärvi', 'Finland', '12/20/2024', 32);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (599, '97', 'Gachancipá', 'Colombia', '3/29/2024', 34);
insert into Koncert (id_koncert, id_turneja, kraj, drzava, datum, cena_karte) values (600, '97', 'Otterburn Park', 'Canada', '1/31/2024', 35);
