insert into turneja (id_turneja, id_album, ime_albuma) values (1, '41GuZcammIkupMPKH2OJ6I', ' ASTROWORLD');
insert into turneja (id_turneja, id_album, ime_albuma) values (2, '6i6folBtxKV28WX3msQ4FE', ' Bohemian Rhapsody (The Original Soundtrack)');
insert into turneja (id_turneja, id_album, ime_albuma) values (3, '1ATL5GLyefJaxhQzSPVrLX', ' Scorpion');
insert into turneja (id_turneja, id_album, ime_albuma) values (4, '6trNtQUgC8cgbWcqoMYkOR', ' beerbongs & bentleys');
insert into turneja (id_turneja, id_album, ime_albuma) values (5, '1qsQOC4Jn0fnaUZLAbs4dz', ' SKINS');
insert into turneja (id_turneja, id_album, ime_albuma) values (6, '4iF44RCCybJtkBkMoqrLW2', ' Street Gossip');
insert into turneja (id_turneja, id_album, ime_albuma) values (7, '6tkjU4Umpo79wwkgPMV3nZ', ' Goodbye & Good Riddance');
insert into turneja (id_turneja, id_album, ime_albuma) values (8, '3tx8gQqWbGwqIGZHqDNrGe', ' Sweetener');
insert into turneja (id_turneja, id_album, ime_albuma) values (9, '4KdtEKjY3Gi0mKiSdy96ML', ' Invasion of Privacy');
insert into turneja (id_turneja, id_album, ime_albuma) values (10, '3JfSxDfmwS5OeHPwLSkrfr', ' Origins (Deluxe)');
insert into turneja (id_turneja, id_album, ime_albuma) values (11, '50yFYgKdwJANZ5O9MIbMkg', ' Tha Carter V');
insert into turneja (id_turneja, id_album, ime_albuma) values (12, '2Ti79nwTsont5ZHfdxIzAm', ' ?');
insert into turneja (id_turneja, id_album, ime_albuma) values (13, '3T4tUhGYeRNVUGevb0wThu', ' ÷ (Deluxe)');
insert into turneja (id_turneja, id_album, ime_albuma) values (14, '7fRrTyKvE4Skh93v97gtcU', ' dont smile at me');
insert into turneja (id_turneja, id_album, ime_albuma) values (15, '3HNnxK7NgLXbDoxRZxNWiR', ' Kamikaze');
insert into turneja (id_turneja, id_album, ime_albuma) values (16, '1WMVvswNzB9i2UMh9svso5', ' The Beatles');
insert into turneja (id_turneja, id_album, ime_albuma) values (17, '5s0rmjP8XOPhP6HhqOhuyC', ' Stoney (Deluxe)');
insert into turneja (id_turneja, id_album, ime_albuma) values (18, '6kf46HbnYCZzP6rjvQHYzg', ' American Teen');
insert into turneja (id_turneja, id_album, ime_albuma) values (19, '33pt9HBdGlAbRGBHQgsZsU', ' Evolve');
insert into turneja (id_turneja, id_album, ime_albuma) values (20, '2acDkDTWdNFie1HjcFa4Ny', ' Queen');
insert into turneja (id_turneja, id_album, ime_albuma) values (21, '5VdyJkLe3yvOs0l4xXbWp0', ' 17');
insert into turneja (id_turneja, id_album, ime_albuma) values (22, '2lATw9ZAVp7ILQcOKPCPqp', ' Love Yourself 結 ''Answer''');
insert into turneja (id_turneja, id_album, ime_albuma) values (23, '2VP96XdMOKTXefI8Nui23s', ' Shawn Mendes');
insert into turneja (id_turneja, id_album, ime_albuma) values (24, '4UNwL1B7JoymNUiTFJa52B', ' Suncity');
insert into turneja (id_turneja, id_album, ime_albuma) values (25, '4eLPsYPBmXABThSJ821sqY', ' DAMN.');
insert into turneja (id_turneja, id_album, ime_albuma) values (26, '6DEjYFkNZh67HP7R9PSZvv', ' reputation');
insert into turneja (id_turneja, id_album, ime_albuma) values (27, '7yf9ZJyHRbp8sHtpDKfPpt', ' Harder Than Ever');
insert into turneja (id_turneja, id_album, ime_albuma) values (28, '0ETFjACtuP2ADo6LFhL6HN', ' Abbey Road (Remastered)');
insert into turneja (id_turneja, id_album, ime_albuma) values (29, '6ZvDJs17O3woQirttKRYCG', ' Sick Boy');
insert into turneja (id_turneja, id_album, ime_albuma) values (30, '6X1x82kppWZmDzlXXK3y3q', ' Take Care (Deluxe)');
insert into turneja (id_turneja, id_album, ime_albuma) values (31, '1zUY4PAFrNUOCeaEBrEHzh', ' Curtain Call: The Hits');
insert into turneja (id_turneja, id_album, ime_albuma) values (32, '63MKT9hwmiMFFdFp5SdB1p', ' Under The Mistletoe (Deluxe Edition)');
insert into turneja (id_turneja, id_album, ime_albuma) values (33, '2vD3zSQr8hNlg0obNel4TE', ' Camila');
insert into turneja (id_turneja, id_album, ime_albuma) values (34, '1KOmHyNLuOe5YrPhD3Juuf', ' Perception');
insert into turneja (id_turneja, id_album, ime_albuma) values (35, '4PgleR09JVnm3zY1fW3XBA', ' 24K Magic');
insert into turneja (id_turneja, id_album, ime_albuma) values (36, '1uG9cIT7IRuq9NqFvKFUsI', ' Greatest Hits II (Remastered)');
insert into turneja (id_turneja, id_album, ime_albuma) values (37, '40GMAhriYJRO1rsY4YdrZb', ' Views');
insert into turneja (id_turneja, id_album, ime_albuma) values (38, '6nxDQi0FeEwccEPJeNySoS', ' Night Visions');
insert into turneja (id_turneja, id_album, ime_albuma) values (39, '4Wv5UAieM1LDEYVq5WmqDd', ' KOD');
insert into turneja (id_turneja, id_album, ime_albuma) values (40, '7GjG91tyHQNGEHzKJaqOi0', ' hopeless fountain kingdom (Deluxe)');
insert into turneja (id_turneja, id_album, ime_albuma) values (41, '1xn54DMo2qIqBuMqHtUsFd', ' x (Deluxe Edition)');
insert into turneja (id_turneja, id_album, ime_albuma) values (42, '2ODvWsOgouMbaA5xf0RkJe', ' Starboy');
insert into turneja (id_turneja, id_album, ime_albuma) values (43, '1lXY618HWkwYKJWBRYR4MK', ' More Life');
insert into turneja (id_turneja, id_album, ime_albuma) values (44, '7viNUmZZ8ztn2UB4XB3jIL', ' 2014 Forest Hills Drive');
insert into turneja (id_turneja, id_album, ime_albuma) values (45, '0SukGZiXMtmsZoxstkBtNR', ' Aura');
insert into turneja (id_turneja, id_album, ime_albuma) values (46, '1yGbNOtRIgdIiGHOEBaZWf', ' 1989 (Deluxe)');
insert into turneja (id_turneja, id_album, ime_albuma) values (47, '42WVQWuf1teDysXiOupIZt', ' Birds In The Trap Sing McKnight');
insert into turneja (id_turneja, id_album, ime_albuma) values (48, '3zak0kNLcOY5vFcB3Ipskp', ' Heartbreak on a Full Moon');
insert into turneja (id_turneja, id_album, ime_albuma) values (49, '7vEJAtP3KgKSpOHVgwm3Eh', ' 1 (Remastered)');
insert into turneja (id_turneja, id_album, ime_albuma) values (50, '3OZgEywV4krCZ814pTJWr7', ' Dangerous Woman');
insert into turneja (id_turneja, id_album, ime_albuma) values (51, '0P3oVJBFOv3TDXlYRhGL7s', ' Beauty Behind The Madness');
insert into turneja (id_turneja, id_album, ime_albuma) values (52, '6QaVfG1pHYl1z15ZxkvVDW', ' Sgt. Pepper''s Lonely Hearts Club Band (Remastered)');
insert into turneja (id_turneja, id_album, ime_albuma) values (53, '4UlGauD7ROb3YbVOFMgW5u', ' ANTI (Deluxe)');
insert into turneja (id_turneja, id_album, ime_albuma) values (54, '4s05NbwGgw5SO42AdsN5Oo', ' Odisea');
insert into turneja (id_turneja, id_album, ime_albuma) values (55, '08jWgM4vSkTose4blKBWov', ' In The Lonely Hour');
insert into turneja (id_turneja, id_album, ime_albuma) values (56, '2ZUFSbIkmFkGag000RWOpA', ' Nothing Was The Same (Deluxe)');
insert into turneja (id_turneja, id_album, ime_albuma) values (57, '5pQwQRnQOuKrbVUVnGMEN4', ' Real Hasta la Muerte');
insert into turneja (id_turneja, id_album, ime_albuma) values (58, '6J84szYCnMfzEcvIcfWMFL', ' Doo-Wops & Hooligans');
insert into turneja (id_turneja, id_album, ime_albuma) values (59, '3wBabo4pmzsYjALMSKY7Iq', ' Illuminate (Deluxe)');
insert into turneja (id_turneja, id_album, ime_albuma) values (60, '3TJz2UBNYJtlEly0sPeNrQ', ' The Thrill Of It All (Special Edition)');
insert into turneja (id_turneja, id_album, ime_albuma) values (61, '3vpXJ54S3MXLyzysw8qq7c', ' Revenge');
insert into turneja (id_turneja, id_album, ime_albuma) values (62, '5OZJflQcQCdZLQjtUudCin', ' BADLANDS (Deluxe)');
insert into turneja (id_turneja, id_album, ime_albuma) values (63, '5fPglEDz9YEwRgbLRvhCZy', ' Graduation');
insert into turneja (id_turneja, id_album, ime_albuma) values (64, '750APP0eKVlcgOxaZnBnVt', ' Too Hard');
insert into turneja (id_turneja, id_album, ime_albuma) values (65, '0ptlfJfwGTy0Yvrk14JK1I', ' If You''re Reading This It''s Too Late');
insert into turneja (id_turneja, id_album, ime_albuma) values (66, '6Fr2rQkZ383FcMqFyT7yPr', ' Purpose (Deluxe)');
insert into turneja (id_turneja, id_album, ime_albuma) values (67, '5rbJtzuXtpIP0Ykk7ewIit', ' 7');
insert into turneja (id_turneja, id_album, ime_albuma) values (68, '5BGzOpea6At0Nd7tYtYZOP', ' Tha Carter III');
insert into turneja (id_turneja, id_album, ime_albuma) values (69, '4JPguzRps3kuWDD5GS6oXr', ' Memories...Do Not Open');
insert into turneja (id_turneja, id_album, ime_albuma) values (70, '39P7VD7qlg3Z0ltq60eHp7', ' I AM...SASHA FIERCE');
insert into turneja (id_turneja, id_album, ime_albuma) values (71, '47BiFcV59TQi2s9SkBo2pb', ' Recovery');
insert into turneja (id_turneja, id_album, ime_albuma) values (72, '7oc6i8xUILaWwQ5BJMZS3c', ' Tha Carter IV (Deluxe)');
insert into turneja (id_turneja, id_album, ime_albuma) values (73, '7gsWAHLeT0w7es6FofOXk1', ' The Life Of Pablo');
insert into turneja (id_turneja, id_album, ime_albuma) values (74, '5kprdYds6oZb4iSldfflOT', ' Vibras');
insert into turneja (id_turneja, id_album, ime_albuma) values (75, '6Ew52HWkgfbth9ihRAq2Xd', ' BEASTMODE 2');
insert into turneja (id_turneja, id_album, ime_albuma) values (76, '0U6ldwLBEMkwgfQRY4V6D2', ' Revival');
insert into turneja (id_turneja, id_album, ime_albuma) values (77, '2cWBwpqMsDJC1ZUwz813lo', ' The Eminem Show');
insert into turneja (id_turneja, id_album, ime_albuma) values (78, '71QyofYesSsRMwFOTafnhB', ' Coloring Book');
insert into turneja (id_turneja, id_album, ime_albuma) values (79, '4PWBTB6NYSKQwfo79I3prg', ' Rodeo (Expanded Edition)');
insert into turneja (id_turneja, id_album, ime_albuma) values (80, '2jJfnAZE6IG3oYnUv2eCj4', ' Love Yourself 轉 ''Tear''');
insert into turneja (id_turneja, id_album, ime_albuma) values (81, '3HHp5I6Q6SEyU5bkvoCtnV', ' The Bigger Artist');
insert into turneja (id_turneja, id_album, ime_albuma) values (82, '6rRFeV6xigfNyPoZ6YqcoW', ' Smoke + Mirrors (Deluxe)');
insert into turneja (id_turneja, id_album, ime_albuma) values (83, '22rp3PnM3q2mtTI0OGCzpq', ' Collage EP');
insert into turneja (id_turneja, id_album, ime_albuma) values (84, '2FTS6a6DLXMNp8flyA0HGO', ' Love Yourself 承 ''Her''');
insert into turneja (id_turneja, id_album, ime_albuma) values (85, '20r762YmB5HeofjMCiPMLv', ' My Beautiful Dark Twisted Fantasy');
insert into turneja (id_turneja, id_album, ime_albuma) values (86, '7Dj0aaKI4RpehMPqOu56mW', ' Beach House 3');
insert into turneja (id_turneja, id_album, ime_albuma) values (87, '4jTYApZPMapg56gRycOn0D', ' Red (Big Machine Radio Release Special)');
insert into turneja (id_turneja, id_album, ime_albuma) values (88, '0fUy6IdLHDpGNwavIlhEsl', ' DS2 (Deluxe)');
insert into turneja (id_turneja, id_album, ime_albuma) values (89, '6opJjTuHd4tQ1h2qrus7jH', ' International Artist');
insert into turneja (id_turneja, id_album, ime_albuma) values (90, '0xi4cOWPUHjctyYU8ypCOB', ' Joytime II');
insert into turneja (id_turneja, id_album, ime_albuma) values (91, '6MoaDh76Fsg0ogW2l7HAFx', ' F.A.M.E.');
insert into turneja (id_turneja, id_album, ime_albuma) values (92, '0CnQ0JQajNswRjPkNYVG8m', ' Handwritten');
insert into turneja (id_turneja, id_album, ime_albuma) values (93, '3CCnGldVQ90c26aFATC1PW', ' 4 Your Eyez Only');
insert into turneja (id_turneja, id_album, ime_albuma) values (94, '1NfrmcXk8xNennyxQ57JcW', ' Born Sinner');
insert into turneja (id_turneja, id_album, ime_albuma) values (95, '5EbpxRwbbpCJUepbqVTZ1U', ' Trilogy');
insert into turneja (id_turneja, id_album, ime_albuma) values (96, '7dK54iZuOxXFarGhXwEXfF', ' Lemonade');
insert into turneja (id_turneja, id_album, ime_albuma) values (97, '0fhmJYVhW0e4i33pCLPA5i', ' Cole World: The Sideline Story');
insert into turneja (id_turneja, id_album, ime_albuma) values (98, '3EzFY9Rg0PpbADMth746zi', ' Fearless (Big Machine Radio Release Special)');
insert into turneja (id_turneja, id_album, ime_albuma) values (99, '35S1JCj5paIfElT2GODl6x', ' HOMECOMING: THE LIVE ALBUM');
insert into turneja (id_turneja, id_album, ime_albuma) values (100, '40XGTQ7FN6Y3dZXJhKBe96', ' The Pinkprint (International Deluxe Explicit)');
